### ISSUE TITLE
Just thank you for your sharing 

### ISSUE THREAD

**Issue by cavo789** [stmswitcher/ajax-grabber#1]
Hello

I've found your script yesterday and it's a really nice code and approach. I've started to implement it in my open source code (marknotes) for allowing people to take backup of their work.

Need optimisation to f.i. allow batch approach (work with severall files at once) but your code is really clean and easy so should be possible without too many work.

So... Thanks for your sharing !

Christophe

**Comment by stmswitcher** [comment]
Hi Christophe!

Thank you for your kind words, and you're very welcome to use this code as you like :)

I create this class over 2 years ago, maybe I'll get back to it and implement some optimization and improve the code in general whenever I have time.

**Comment by cavo789** [comment]
Hi Denis

I'm just busy on it right now. ;)

Your code (once again very clean) show how to deal with Ajax and avoid timeout but process files one by one. On my localhost, I've a site with 1.500 files or more to archive so 1.500 ajax requets (and I think that my real production server will ban my IP if I do that).

So, I'm coding a "batch" mode : not process files one by one but f.i. 100 files in one call (are small files) or, better, calculate the filesize and stop as soon as the size is bigger than ... MB.

So the next ajax call will, thanks the Offset info, know where to continue.

The code will be released in my next version of marknotes (https://github.com/cavo789/marknotes); if you've interested, I will mention to you when I'll publish this.

(note : the code will be integrated to my own code as a plugin but with a lot of changes to match my needs so can't be used `as is` for your demo).

Have a nice day !

**Comment by cavo789** [comment]
Idea is producing something like

```
[
    {
        "end": false,
        "log_info": "docs\\file1 - success",
        "btn_text": "6\/34",
        "btn_bootstrap_class": "btn-default",
        "offset": 6
    },
    {
        "end": false,
        "log_info": "docs\\file2 - success",
        "btn_text": "7\/34",
        "btn_bootstrap_class": "btn-default",
        "offset": 7
    },
    {
        "end": false,
        "log_info": "docs\\file3 - success",
        "btn_text": "8\/34",
        "btn_bootstrap_class": "btn-default",
        "offset": 8
    },
    {
        "end": false,
        "log_info": "docs\\file4 - success",
        "btn_text": "9\/34",
        "btn_bootstrap_class": "btn-default",
        "offset": 9
    },
    {
        "end": false,
        "log_info": "docs\\file5 - success",
        "btn_text": "10\/34",
        "btn_bootstrap_class": "btn-default",
        "offset": 10
    }
]
```

This is the job of the `req.php` file and the `.js` script just need to detect that the answer is an array and no more a single line.

The next call will then use `offset=10` and just `+1`.

`req.php` will process a static number of files by call (let's say 100) or, better, as many as possible until the processed total size is bigger than xxx MB.

This will improve the speed and reduce HTTP requests (and the risk of being banned (too many requests by the same IP in a very small time)

**Comment by cavo789** [comment]
Hi Denis, 

As promised, for your information, my code has been released a few days ago : https://github.com/cavo789/marknotes/tree/master/src/marknotes/plugins/task/backup.

It's a backup plugin for my Open Source software based on your approach but working in a "batch" mode i.e. zipping several files at once and make a new ZIP file if the current is one is greater than a specified size.

Once more, thanks for you nice .js approach.

Have a nice day.
